### PR TITLE
Sent participant information along with activity detail.

### PR DESCRIPTION
**Pull request by opxz7148**
### Description

- Polished activity detail to return participant data along with their profile picture.
- Remove obsolete get_participant view

### Functional Acceptance Criteria (Not required for Documentation update)

- Response from GET request to /activities/<activity_id>/ should contain activity data and list of participant data with their profile picture.
- Web app should work well without old code.

### Checklist (Not required for Documentation update)

- [x] I have performed a self-review of my code.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [x] Other (API enhancement)

### CODE REVIEW

**Comment by Thanawas-Sirilertsathit** [comment]
image
Calendar date picker still white and participant does not show up

**Review by TeerapatTrepopsakulsin — APPROVED** [review]
- Web app works correctly. _Approve_
- Response from GET request to /activities/<activity_id>/ contain activity data and list of participant data with their profile picture correctly. _Approve_

Some method docstrings doesn't fully follow _sphinx style_, which is the only minor issue I see, and I'll ignore it for now if other reviewers also approve this PR. Overall, excellent work. _Approve_

**Comment by OmegaOoh** [comment]
Please Merge from the main, and resolve the conflict

**Review by Thanawas-Sirilertsathit — CHANGES_REQUESTED** [review]
Your merging cause ActivityDetail page and ActivityEdit modal not working correctly.
From this picture it should show Leave button and Chat button.
image
I will commit the fixed part of ActivityEdit modal for you

**Review by OmegaOoh — APPROVED** [review]
Everything seems good and work well. _approve_

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
Good job, it seems you figured out which attributes you assigned in the ActivityDetail page that you forgot. Now existed features works normally.

**Pull request merged**
