### PR TITLE
Index and Detail UI changes, pagination for index detail(participant) and chat

### LINKED ISSUE #171: Minor Bugs on Activity Edit, Image
**Describe the bug**
After adding and removing the image from the activity edit a few times some images can't be added to the activity until the request and opened to edit again

**To Reproduce**
1. Go to Your activity
2. Click on edit
3. Add and Remove the image a few times
4. Can't add the same picture into an image list

**Expected behavior**
The removed image should be able to add to the activity.

### LINKED ISSUE #222: Minor format change to index and detail page

### LINKED ISSUE #228: Pagination frontend

### LINKED ISSUE #230: Cancel activity Frontend

### PR DESCRIPTION
**Pull request by OmegaOoh**
### Description

- pagination for index detail(participant) and chat
- improved data shown on index and detail
- handle cancelled activities

Closes #222, closes #171, closes #228, closes #230 

### Functional Acceptance Criteria (Not required for Documentation update)

- Only 20 activities loaded at first and loaded more on scrolling down
- Only 20 participants show on each participant page
- Chat messages have 20 initial loads. and load more by scrolling up
- Cancelled activities do not appear on the index page.
- Make activities unable to be edited for some reason (After cancelled, After activity ended).

### Checklist (Not required for Documentation update)

- [x] I have performed a self-review of my code.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### Additional Information (Optional)

Further information about pull request.

### CODE REVIEW

**Comment by Thanawas-Sirilertsathit** [comment]
image

It appears only join button even I am the host of activity or already joined participant.

**Comment by Thanawas-Sirilertsathit** [comment]
image

Host unable to access chat

**Comment by opxz7148** [comment]
Screenshot 2567-11-16 at 12 58 17
End date field disappear from edit activity. is this intended?

**Comment by Thanawas-Sirilertsathit** [comment]
Enddate field is back

**Review by opxz7148 — APPROVED** [review]
Every acceptance criteria are met, nice work _Approve_

**Review by TeerapatTrepopsakulsin — COMMENTED** [review]
Pretty UI, the acceptance criteria are met, but now I cannot use filter and search (Bug).

**Review by TeerapatTrepopsakulsin — APPROVED** [review]
_Approve_

**Pull request merged**
