### PR TITLE
User joined activity

### PR DESCRIPTION
**Pull request by TeerapatTrepopsakulsin**
### Description

- `active_joined_activities` class method in Attend returning all active activities for a user, with user as a parameter.
- `recently_joined` class method in Attend returning 3 latest activities joined by user, with user as a parameter.

### Functional Acceptance Criteria

- `Attend.active_joined_activities(user)` returns all activities joined by user, order by activity date.
- `Attend.recently_joined(user)` returns 3 latest activities joined by user, order by join time (attend_id).

### Checklist

- [x] I have performed a self-review of my code.
- [x] I have added tests to cover my changes.
- [x] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### CODE REVIEW

**Comment by Thanawas-Sirilertsathit** [comment]
Well we might pass to api after this.

**Comment by Thanawas-Sirilertsathit** [comment]
Also merge your branch from main first

**Comment by Thanawas-Sirilertsathit** [comment]
Even I fixed that testcase

**Review by OmegaOoh — APPROVED** [review]
Every function worked, but Can't access past activity which is intended. You can make the `warning` alert to let users know why they aren't redirected.

**Review by OmegaOoh — APPROVED** [review]
Everything works as intended, and an alert for when the user can't access the activity. good job.

**Review by opxz7148 — APPROVED** [review]
Recent activity show as intended also can't access activity that already unavailable. For a suggestion I think recent activity list should be a dropdown menu. But for now it's ok to merge _Approve_

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
No extra changes needed now

**Pull request merged**
