### PR TITLE
Format import statement

### PR DESCRIPTION
**Pull request by opxz7148**
### Description

- Improve import statement order

### Functional Acceptance Criteria

- Application still work as before

### Checklist (Not required for Documentation update)

- [x] I have performed a self-review of my code.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Other (Enchancement)

### CODE REVIEW

**Review by OmegaOoh — APPROVED** [review]
Good job reordering python imports

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
Functionality works well after reformat.

**Review by TeerapatTrepopsakulsin — APPROVED** [review]
Thx for doing these tiny tasks. _Approve_

**Comment by opxz7148** [comment]
Wow 3 approve

**Pull request merged**
