### PR TITLE
Frontend ui changes: recolor, refactor, add search bar.

### PR DESCRIPTION
**Pull request by OmegaOoh**
### Description

- Recolor of entire page #107 #109
- Role related action #126
- Add a search bar. #124
- Leave a button on the detail page. #114
- Change edit to modal to detail page #108 
- Enforce some form of control from the front end to prevent some errors from inputs. #110
- Organize function in the front end.
- Add a placeholder for profile picture, use of Vue-Lazyload

### Functional Acceptance Criteria

1. Users can access all the pages according to their status in the activity
    1. Activity detail page
        1. Hosts: Chat, Edit
        2. Participants: Chat, Leave
        3. Visitor (Not authenticated): Login 
        4. User (Authenticated, but is not a participant): Join (disable if cannot be joined)
    2. Chat page
        1. Participants, Host: Chat UI
        2. User (Authenticated, but is not a participant): The button leads to the detail page.
        3. Visitor: Propmt to log in.
    3. Navbar
        1. User: Create Activity on the drawer, User Profile with dropdown to logout
        2. Visitor: No drawer, login button
2. The user can navigate to all pages without manually editing the URL
3. All profile picture has a placeholder in case of error.

### Checklist
- [x] I have performed a self-review of my code.
- [ ] I have added tests to cover my changes.
- [ ] My code follows the Coding Guidelines.

### Type of Change

- [x] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### CODE REVIEW

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
User interface looks more beautiful and has function for searching, leave button, nav_bar and better button display in ActivityDetail page.

**Review by TeerapatTrepopsakulsin — COMMENTED** [review]
Overall, wonderful work. UI looks pretty, nice navigation, and good code too! but I found some bugs and have several personal opinion about the activity detail page.

Detail page:
 - Bug
   - 1)create activity 2) send message 3) navigate back to detail page 4) **Host can leave activity (just like participants)** 
 - Suggestion
   - After editing, I have to refresh 1 time for information to be updated.
   - The edit button doesn't stand out, personally (doesn't look like I'm the host).
   - I prefer it to show activity name instead of ID   
image

**Comment by OmegaOoh** [comment]
> Overall, wonderful work. UI looks pretty, nice navigation, and good code too! but I found some bugs and have several personal opinion about the activity detail page.
> 
> Detail page:
> 
> * Bug
>   
>   * 1)create activity 2) send message 3) navigate back to detail page 4) **Host can leave activity (just like participants)**
> * Suggestion
>   
>   * After editing, I have to refresh 1 time for information to be updated.
>   * The edit button doesn't stand out, personally (doesn't look like I'm the host).
>   * I prefer it to show activity name instead of ID
>     image

Fixed most of it. Please rereview

**Review by TeerapatTrepopsakulsin — APPROVED** [review]
Quick quality work. _Approve_

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
UI looks beautiful and chat now works well.

From Teerapat comment about nav bar, I prefer using id because the Activity title can be very long and it may not look good.

**Pull request merged**
