### PR TITLE
Backend function for searching the activity

### PR DESCRIPTION
**Pull request by TeerapatTrepopsakulsin**
Currently, it works for only the backend.

- Can now use query parameter `keyword` to filter activities name (i.e. `http://localhost:8000/activities/?keyword=value` with `value` for filter)

### CODE REVIEW

**Comment by TeerapatTrepopsakulsin** [comment]
@opxz7148 I've put the keyword part to get_query instead. You can review it again.

**Comment by TeerapatTrepopsakulsin** [comment]
## Title: Backend function for searching the activity

### Description
- Keyword search function in ActivityIndex
  - Overwrite get_queryset in ActivityIndex, so that the page only shows activities that match the keyword.

### Functional Acceptance Criteria
- Search by keyword (ActivityIndex)
  - Can now use query parameter `keyword` to filter activities name (i.e. `http://localhost:8000/activities/?keyword=value` with `value` for filter)

### Checklist
- [x] I have performed a self-review of my code.
- [x] I have added tests to cover my changes.
- [x] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### Additional Information
- Does this PR introduce a breaking change? No
  
- Other information:
  - Only works for the backend.

**Review by opxz7148 — APPROVED** [review]
Great job, search work well.

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
Backend function works well, I tried in django backend webpage. All the tests passed. OK!

**Pull request merged**
