### PR TITLE
Search bar and filter by day and date range

### PR DESCRIPTION
**Pull request by Thanawas-Sirilertsathit**
### Description

- In ActivityIndex page, there are dropdown for filtering days and datepicker to filter the date range.
- You can use multiple filter options with search bar at the same time.

### Functional Acceptance Criteria

- #173 
- User can filter activities using multiple options at the same time. (Date range, Day and Keyword)

### Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other

### CODE REVIEW

**Review by opxz7148 — CHANGES_REQUESTED** [review]
Filtering work well. Only activity that meet filter condition appear but there are 1 defect here. Look like Su and Sa should swap there position.
Screenshot 2567-11-03 at 13 11 05

**Comment by Thanawas-Sirilertsathit** [comment]
👍

**Review by opxz7148 — APPROVED** [review]
Sunday and Saturday are in the correct position nice. I suggest that filter should have reset button to reset all filter. But for now _Approve_

**Review by TeerapatTrepopsakulsin — APPROVED** [review]
Filtering works well without any problems. _Approve_

**Pull request merged**
