### PR TITLE
Host reputation point decrease

### PR DESCRIPTION
**Pull request by TeerapatTrepopsakulsin**
### Description

- #227 

### Functional Acceptance Criteria

- After end_date or the activity get cancelled, if no participants are checked-in or activity is cancelled, the host reputation point will be deducted. (Similar to point deducted for individual participant)

### Checklist

- [x] I have performed a self-review of my code.
- [x] I have added tests to cover my changes.
- [ ] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### CODE REVIEW

**Comment by Thanawas-Sirilertsathit** [comment]
You forgot a case that activity is cancelled and attendee reputation points should not be decreased.

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
All logic of reputation decrease met requirements.

**Review by Thanawas-Sirilertsathit — CHANGES_REQUESTED** [review]
Your filter activities are only for enddate not for cancelled activities. You should filter for cancelled activities and enddate. Otherwise the reputation score will be deducted after enddate. I want after cancel it reduce the reputation score.

**Comment by TeerapatTrepopsakulsin** [comment]
> Your filter activities are only for enddate not for cancelled activities. You should filter for cancelled activities and enddate. Otherwise the reputation score will be deducted after enddate. I want after cancel it reduce the reputation score.

Thanks for pointing it out. I've included the is_cancelled in the filter now.

**Review by Thanawas-Sirilertsathit — CHANGES_REQUESTED** [review]
OK, One last thing I found is concurrent activities. After check-in (Mean you done the activity), activity cancelled and pass the end_date, the concurrent activities should be decreased. For now I see only it check the start_date of activity which should not be.

**Review by Thanawas-Sirilertsathit — COMMENTED** [review]
Also I can infinitely check-in activity. Idk but it happens

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
From your code, all logic suppose to cover all cases now.

**Review by opxz7148 — APPROVED** [review]
Acceptance criteria were met _Approve_

**Pull request merged**
