### PR TITLE
Logging to file

### PR DESCRIPTION
**Pull request by TeerapatTrepopsakulsin**
### Description

- Logging INFO and WARNING to file #205

### Functional Acceptance Criteria

- The logging shows correct log messages according to the scenario. _Detail in Additional Information_

### Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests to cover my changes.
- [x] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [x] Other (Logging)

### Additional Information
- Settings
    + 3 Handlers:
      * `console` - log to console
      * `activities-file` log to `activities.log` file
      * `profiles-file` log to `profiles.log` file

- Activities
    + INFO
      * Create
      * Join
      * Leave
      * Edit
      * Kick
      * Grant/Remove host
      * Check-in
      * Open check-in
      * Close Check-in
    + WARNING
      * Fail to create (No profile)
      * Fail to create (Owner Rep < min_rep)
      * Fail to join (No profile)
      * Fail to join (#Join reach limit)
      * Fail to join (Not active)
      * Fail to join (Full)
      * Fail to join (Rep too low)
      * Fail to join (Already join)
      * Fail to edit (Owner Rep < min_rep)
      * Fail to edit (Current people > max_people)
      * Fail to check-in (Not member)
      * Fail to check-in (Check-in not allow)
      * Fail to check-in (Invalid code)
      * Fail to open check-in (Not in check-in period)
      * Fail to edit host access (Not owner)
- Profiles
    + INFO
      * Edit
      * Create
    + WARNING
      * Try to edit other profile
      * Fail to create (already exist)

### CODE REVIEW

**Review by OmegaOoh — CHANGES_REQUESTED** [review]
Your logging has separated modules which is fine. BUT the logging message got the pattern for examples. `<User> <action> <Act> <reason>` and currently write it every where by hands. AS you already have a logging module, you should define the function or constant to eliminate the repeats of the log message you need to write. (It also violates DRY)

**Comment by TeerapatTrepopsakulsin** [comment]
> Your logging has separated modules which is fine. BUT the logging message got the pattern for examples. `<User> <action> <Act> <reason>` and currently write it every where by hands. AS you already have a logging module, you should define the function or constant to eliminate the repeats of the log message you need to write. (It also violates DRY)

Edited. Please review.

**Review by OmegaOoh — CHANGES_REQUESTED** [review]
Info and warning do same thing how comes it a separate function

**Review by OmegaOoh — CHANGES_REQUESTED** [review]
More of it, you can introduce object parameter to shorten the params list. you should use logger.log('level', msg) instead of hard code the level

**Comment by TeerapatTrepopsakulsin** [comment]
> Info and warning do same thing how comes it a separate function

Strategy method. Personally, I think it's easier to understand if the log level is the module function instead of the function parameter.

**Comment by OmegaOoh** [comment]
> > Info and warning do same thing how comes it a separate function
> 
> Strategy method. Personally, I think it's easier to understand if the log level is the module function instead of the function parameter.

So if I want to use FATAL or ERROR I need to create new method?

Too much work for a little thing

**Review by opxz7148 — CHANGES_REQUESTED** [review]
What I think you can to improve this.

- Create a class that hold logger as an attribute. Along with a necessary information such as req_user, activity/profile_id etc. and create an instance before actual logging anything. This will make code more cleaner.
- Inside that class create a name constant for each action and use that instead of raw string
- make a log method inside that class which invoke logger.log() with a level (which are constant inside logging) instead of use logger.warn() logger.info() which that class hold as a attribute. By take an action, reason, level as a param. then do you thing with convert to log_msg with will be a private method inside a class then logger.log it.

But if you think it's to much or any better way try to do it

**Review by OmegaOoh — APPROVED** [review]
I think this is correct overall.

**Review by opxz7148 — APPROVED** [review]
Logging is correct and have good quality, nice. _Approve_

**Pull request merged**
