### PR TITLE
README revision

### PR DESCRIPTION
**Pull request by OmegaOoh**
### Description

- shorten the readme to be simpler and easier to read,
- Installation guide is on the separated file.

### Type of Change

- [ ] Bug fix
- [ ] New feature
- [x] Documentation update
- [ ] Other (please specify)

### CODE REVIEW

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
README is more clearly seperate the installation part to installation.md.

**Review by TeerapatTrepopsakulsin — APPROVED** [review]
Just add badges and revise a little bit. Installation is moved as it should. _Approve_

**Review by opxz7148 — APPROVED** [review]
There are some obsolete instruction inside google credentials guide, but I already remove by myself _Approve_

**Review by Thanawas-Sirilertsathit — APPROVED** [review]
Nice, removed obsolete code that I forgot.

**Pull request merged**
