### PR TITLE
Multiple host

### PR DESCRIPTION
**Pull request by TeerapatTrepopsakulsin**
### Description

- #184 
- Page for activity owner to grant or remove host access to participants #185
- #196 
- #201 

### Functional Acceptance Criteria

- When creating an activity, the user who creates it will become the owner of the activity, which will be stored to the database
- Activity detail view handles PUT requests correctly. See detail in _Additional Information_
- Only the owner (Must be the owner) can grant and remove participants (Must be participants, other than the owner) host access.
- In detail page click on (Manage participant), owner can give participant permission to become host. On the other hand, he can also revoke that permission.

### Checklist

- [x] I have performed a self-review of my code.
- [x] I have added tests to cover my changes.
- [ ] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### Additional Information

- `PUT  /activities/<int:pk>`
    + example: request data: `{"grant_host": [100]}` -> Attend object of user whose id is 100 and activity, is_host become True
     request data: `{"remove_host": [100]}` -> Attend object of user whose id is 100 and activity, is_host become False

### CODE REVIEW

**Review by OmegaOoh — CHANGES_REQUESTED** [review]
I and @Thanawas-Sirilertsathit dicussed and conclude that
1. The API endpoint doesn't look RESTful
2. It does have the responsibility of modifying the activity as same as `PUT ../activity/<int: pk>`

Please fix it. No excuses

**Comment by TeerapatTrepopsakulsin** [comment]
> I and @Thanawas-Sirilertsathit dicussed and conclude that
> 
> 1. The API endpoint doesn't look RESTful
> 2. It does have the responsibility of modifying the activity as same as `PUT ../activity/<int: pk>`
> 
> Please fix it. No excuses

I edited it. Please give it a review.
Also, check the PR template changes too.

**Review by OmegaOoh — CHANGES_REQUESTED** [review]
Everything looks good, but the Description of API endpoints and needed data is too vague. What is 100?

The check-in should be updated after someone become host

**Review by opxz7148 — APPROVED** [review]
Multiple host look well _Approve_

**Review by OmegaOoh — APPROVED** [review]
I think the codes look goods, all docstring are written in Sphinx

**Review by opxz7148 — CHANGES_REQUESTED** [review]
promoted host can't close check-in

**Review by opxz7148 — CHANGES_REQUESTED** [review]
promoted host can't close check-in

**Review by opxz7148 — APPROVED** [review]
Ignore previous request change _Approve_

**Pull request merged**
